### ISSUE TITLE
Nothing worked

### ISSUE THREAD

**Issue by XinyueZ** [RizwanMunawar/yolov5-object-tracking#4]
``` 
python obj_det_and_trk.py --weights yolov5s.pt --source ./assets/0_043.mp4 --blur-obj
Traceback (most recent call last):
  File "/home/ubuntu/work/yolov5-object-tracking/obj_det_and_trk.py", line 29, in <module>
    from sort import *
  File "/home/ubuntu/work/yolov5-object-tracking/sort.py", line 6, in <module>
    matplotlib.use('TkAgg')
  File "/home/ubuntu/miniconda3/envs/yolov5objtracking/lib/python3.9/site-packages/matplotlib/__init__.py", line 1237, in use
    plt.switch_backend(name)
  File "/home/ubuntu/miniconda3/envs/yolov5objtracking/lib/python3.9/site-packages/matplotlib/pyplot.py", line 279, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

**Comment by mahilaMoghadami** [comment]
hello
in sort.py file, change matplotlib.use('TKAgg') to matplotlib.use('Agg')
it works for me.

**Comment by animeesh** [comment]
commenting the whole line can also do!
#matplotlib.use('TkAgg')
